-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 16:06:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imprimindo_inclusao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imprimindo_inclusao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imprimindo_inclusao` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `imprimindo_inclusao` ;

-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `identificador` VARCHAR(150) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `perfil` ENUM('ADMIN', 'EMPRESA', 'FUNCIONARIO') NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `identificador_UNIQUE` (`identificador` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `email` VARCHAR(50) UNIQUE NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idempresa`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `imprimindo_inclusao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`doacao` (
  `iddoacao` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `tipo` ENUM('FILAMENTO', 'IMPRESSORA') NOT NULL,
  `descricao` TEXT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT '1',
  `data_manifestacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `visualizada` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`iddoacao`),
  INDEX `fk_doacao_empresa` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_doacao_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `imprimindo_inclusao`.`empresa` (`idempresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `setor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `imprimindo_inclusao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`impressora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`impressora` (
  `idimpressora` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(100) NOT NULL,
  `disponibilidade` ENUM('OCIOSA', 'EM_USO') NOT NULL DEFAULT 'OCIOSA',
  `ativo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idimpressora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imprimindo_inclusao`.`solicitacao_impressao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imprimindo_inclusao`.`solicitacao_impressao` (
    `idsolicitacao_impressao` INT NOT NULL AUTO_INCREMENT,
    `empresa_id` INT NOT NULL,
    `criado_por` INT NOT NULL,
    `impressora_id` INT NULL DEFAULT NULL,
    `titulo` VARCHAR(100) NOT NULL,
    `descricao` TEXT NOT NULL,
    `arquivo_modelo` VARCHAR(255) NOT NULL,
    `quantidade` INT NOT NULL DEFAULT '1',
    `status` ENUM('PENDENTE','EM_ANDAMENTO','RECUSADA','CANCELADA','CONCLUIDA','FALHOU') NOT NULL DEFAULT 'PENDENTE',
    `justificativa` TEXT NULL DEFAULT NULL,
    `cancelado_por` INT NULL DEFAULT NULL,
    `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `data_decisao` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`idsolicitacao_impressao`),
    INDEX `idx_solicitacao_status` (`status` ASC) VISIBLE,
    INDEX `fk_solicitacao_empresa` (`empresa_id` ASC) VISIBLE,
    INDEX `fk_solicitacao_criado_por` (`criado_por` ASC) VISIBLE,
    INDEX `fk_solicitacao_impressora` (`impressora_id` ASC) VISIBLE,
    INDEX `fk_solicitacao_cancelado_por` (`cancelado_por` ASC) VISIBLE,
    CONSTRAINT `fk_solicitacao_empresa`
    FOREIGN KEY (`empresa_id`) REFERENCES `imprimindo_inclusao`.`empresa` (`idempresa`),
    CONSTRAINT `fk_solicitacao_criado_por`
    FOREIGN KEY (`criado_por`) REFERENCES `imprimindo_inclusao`.`funcionario` (`idfuncionario`),
    CONSTRAINT `fk_solicitacao_impressora`
    FOREIGN KEY (`impressora_id`) REFERENCES `imprimindo_inclusao`.`impressora` (`idimpressora`),
    CONSTRAINT `fk_solicitacao_cancelado_por`
    FOREIGN KEY (`cancelado_por`) REFERENCES `imprimindo_inclusao`.`usuario` (`idusuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;